import { ContentTreeView as ContentTreeView_0cfcbe9cef09beab3e91100486fab181 } from '@garsoncron/payload-plugin-content-tree/client'
import { CollectionCards as CollectionCards_f9c02e79a4aed9a3924487c0cd4cafb1 } from '@payloadcms/next/rsc'
import { TreeWithPuck as TreeWithPuck_f7a3e9d2c1b04e5a8f6d7c2e3a4b5f6e } from '../../../components/TreeWithPuck.js'

/**
 * Payload import map — auto-generated by `payload generate:importmap`.
 *
 * This file is committed as a starting-point. On `pnpm dev` or `pnpm build`,
 * Payload regenerates it from the component paths declared in payload.config.ts.
 * Commit the regenerated version after first run.
 *
 * @type import('payload').ImportMap
 */
export const importMap = {
  '@garsoncron/payload-plugin-content-tree/client#ContentTreeView':
    ContentTreeView_0cfcbe9cef09beab3e91100486fab181,
  '@payloadcms/next/rsc#CollectionCards': CollectionCards_f9c02e79a4aed9a3924487c0cd4cafb1,
  './components/TreeWithPuck#TreeWithPuck': TreeWithPuck_f7a3e9d2c1b04e5a8f6d7c2e3a4b5f6e,
}
